//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booth
    {
        public Booth()
        {
            this.InspectionRequests = new HashSet<InspectionRequest>();
        }
    
        public int Id { get; set; }
        public int Area { get; set; }
        public int Index { get; set; }
        public string Quality { get; set; }
        public int OperatorCount { get; set; }
        public bool ForSell { get; set; }
        public bool ForVitrin { get; set; }
        public bool ForCommision { get; set; }
        public bool HasPhone { get; set; }
        public bool HasCardReader { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Map Map { get; set; }
        public virtual ICollection<InspectionRequest> InspectionRequests { get; set; }
        public virtual BoothRequest BoothRequest { get; set; }
        public virtual BoothExtensionRequest BoothExtensionRequest { get; set; }
    }
}
