//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructAbility
    {
        public int Id { get; set; }
        public int Cost { get; set; }
        public string Profession { get; set; }
        public string Quality { get; set; }
        public int Duration { get; set; }
        public bool Done { get; set; }
    
        public virtual BoothExtensionRequest BoothExtensionRequest { get; set; }
        public virtual BoothConstructor BoothConstructor { get; set; }
    }
}
