//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Id { get; set; }
        public bool HasWareHouse { get; set; }
        public bool HasPostOffice { get; set; }
        public bool HasSell { get; set; }
        public bool HasDifferentBooth { get; set; }
    
        public virtual Exhibition Exhibition { get; set; }
    }
}
