//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionRequest : Request
    {
        public int Fine { get; set; }
        public string ResponseType { get; set; }
    
        public virtual Booth Booth { get; set; }
    }
}
