//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Map
    {
        public Map()
        {
            this.Booths = new HashSet<Booth>();
        }
    
        public int Id { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
    
        public virtual Saloon Saloon { get; set; }
        public virtual ICollection<Booth> Booths { get; set; }
    }
}
