//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.PollChoices = new HashSet<PollChoice>();
            this.PollUsers = new HashSet<PollUser>();
        }
    
        public int Id { get; set; }
        public string Question { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public bool Closed { get; set; }
        public bool FinishByDate { get; set; }
    
        public virtual ICollection<PollChoice> PollChoices { get; set; }
        public virtual ICollection<PollUser> PollUsers { get; set; }
        public virtual Exhibition Exhibition { get; set; }
    }
}
