//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOffice
    {
        public PostOffice()
        {
            this.PostItems = new HashSet<PostItem>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<PostItem> PostItems { get; set; }
        public virtual Exhibition Exhibition { get; set; }
    }
}
