//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public int MinLength { get; set; }
        public int MaxLength { get; internal set; }
        public int StartNode { get; set; }
        public int FinishNode { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
