//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Response { get; set; }
        public bool Responsed { get; set; }
        public bool Agreed { get; set; }
    
        public virtual Exhibition Exhibition { get; set; }
        public virtual User User { get; set; }
    }
}
