//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Modeling
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserExhibitionRoles = new HashSet<UserExhibitionRole>();
            this.PollUsers = new HashSet<PollUser>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Username { get; set; }
        public string FamilyName { get; set; }
        public long PhoneNumber { get; set; }
        public string Password { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserExhibitionRole> UserExhibitionRoles { get; set; }
        public virtual ICollection<PollUser> PollUsers { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
